[package]
name = "bevy_voxel_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8.1", features = ["dynamic"] }
bevy_flycam = "0.8.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
